# Generated by Django 5.0.7 on 2024-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('case_type', models.CharField(max_length=100)),
                ('accuser_name', models.CharField(max_length=255)),
                ('accuser_phone', models.CharField(max_length=15)),
                ('court_date', models.DateField()),
                ('next_court_date', models.DateField()),
                ('investigating_officer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
