# Generated by Django 5.1.1 on 2024-10-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('court_file_number', models.CharField(blank=True, max_length=100, null=True)),
                ('case_type', models.CharField(choices=[('abduction', 'Abduction'), ('defilement', 'Defilement'), ('neglegence', 'Negligence'), ('legal councelling', 'Legal Councelling'), ('emotional abuse', 'Emotional Abuse'), ('child abuse', 'Child Abuse'), ('physical assault', 'Physical Assault'), ('domestic violence', 'Violence'), ('attempted defilement', 'Attempted Defilement'), ('sodomy', 'Sodomy'), ('rape', 'Rape'), ('juvenile deliquency', 'Juvenile Deliquency'), ('attempted sodomy', 'Attempted Sodomy'), ('attempted rape', 'Attempted Rape'), ('sexual assault', 'Sexual Assault'), ('indicent act', 'Incident Act'), ('sexual harrassment', 'Sexual Harrassment')], max_length=100)),
                ('case_registration_date', models.DateField(blank=True, null=True)),
                ('accused_name', models.CharField(max_length=255)),
                ('accuser_name', models.CharField(max_length=255)),
                ('accuser_phone', models.CharField(max_length=15)),
                ('court_name', models.CharField(max_length=255)),
                ('court_date', models.DateField()),
                ('next_court_date', models.DateField()),
                ('police_station', models.CharField(max_length=255, null=True)),
                ('investigating_officer', models.CharField(max_length=255)),
                ('investigating_officer_phone', models.CharField(max_length=15)),
                ('stage_of_case', models.CharField(choices=[('defence hearing', 'Defence Hearing'), ('withdrawn', 'Withdrawn'), ('hearing', 'Hearing'), ('judgement', 'Judgement'), ('mention', 'Mention'), ('rulling', 'Rulling'), ('sentencing_3_years', 'Sentencing for 3 years'), ('jailed_10_years', 'Jailed for 10 years')], max_length=100)),
                ('county', models.CharField(blank=True, choices=[('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana river', 'Tana River'), ('lamu', 'Lamu'), ('taita-taveta', 'Taita-Taveta')], max_length=255, null=True)),
                ('sub_county', models.CharField(blank=True, choices=[('changamwe', ' Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('likoni', 'Likoni'), ('mvita', 'Mvita'), ('nyali', 'Nyali'), ('matuga', 'Matuga'), ('msambweni', 'Msambweni'), ('lunga lunga', 'Lunga Lunga'), ('kinango', 'Kinango'), ('kilifi north', 'Kilifi North'), ('kilifi south', 'Kilifi South'), ('malindi', 'Malindi'), ('magarini', 'Magarini'), ('rabai', 'Rabai'), ('kaloleni', 'Kaloleni'), ('ganze', 'Ganze'), ('gazole', 'Galole'), ('bura', 'Bura'), ('garsen', 'Garsen'), ('lamu east', 'Lamu East'), ('lamu west', 'Lamu West'), ('mwatate', 'Mwatate'), ('voi', 'Voi'), ('taveta', 'Taveta'), ('wundanyi', 'Wundanyi')], max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('ward', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
