# Generated by Django 5.0.7 on 2024-08-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accused_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
