# Generated by Django 5.0.7 on 2024-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_accused_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='accused_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
