# Generated by Django 5.1.1 on 2024-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_case_case_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='jail_duration',
            field=models.IntegerField(blank=True, help_text='Jail duration in months or years', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sentence_duration',
            field=models.IntegerField(blank=True, help_text='Sentencing duration in months or years', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='stage_of_case',
            field=models.CharField(choices=[('defence hearing', 'Defence Hearing'), ('withdrawn', 'Withdrawn'), ('hearing', 'Hearing'), ('judgement', 'Judgement'), ('mention', 'Mention'), ('rulling', 'Rulling'), ('sentencing', 'Sentencing'), ('jailing', 'Jailing')], max_length=100),
        ),
    ]
