# Generated by Django 5.1.1 on 2024-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_jail_duration_case_sentence_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jail_duration',
            field=models.CharField(blank=True, help_text='Jail duration in months or years', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='sentence_duration',
            field=models.CharField(blank=True, help_text='Sentencing duration in months or years', max_length=255, null=True),
        ),
    ]
