# Generated by Django 5.1.1 on 2025-06-10 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_jail_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='court_file_number',
            new_name='assault_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='accused_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='accuser_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='accuser_phone',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='investigating_officer',
        ),
        migrations.RemoveField(
            model_name='case',
            name='investigating_officer_phone',
        ),
        migrations.RemoveField(
            model_name='case',
            name='jail_duration',
        ),
        migrations.RemoveField(
            model_name='case',
            name='location',
        ),
        migrations.RemoveField(
            model_name='case',
            name='next_court_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='case',
            name='sentence_duration',
        ),
        migrations.RemoveField(
            model_name='case',
            name='stage_of_case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='case',
            name='ward',
        ),
        migrations.AddField(
            model_name='case',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_constituency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_duration_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='case_referred_to_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_still_in_court',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_ward_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cleaned_assault_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_case_assignment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_case_closure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_case_intake',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_case_reporting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_court_followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='days_since_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='gender_site_code_of_reporting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_report_constituency_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_report_county_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_report_village_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_report_ward_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_case_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='is_the_case_proceeding_to_court',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='medium_of_reporting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='previous_case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_for_medical_intervention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_to_counseling_and_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_to_dco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_to_other_shofco_programs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_to_police',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='referred_to_safe_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='stage_of_case_in_court',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='survivor_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='survivor_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
