# Generated by Django 5.1.1 on 2025-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_court_file_number_case_assault_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_intake_datekey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_reported_to_police',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_reporting_datekey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_summary_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_safe_house_discharge',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_safe_house_onboarding',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='parent_case_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='parent_case_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
