# Generated by Django 5.0.7 on 2024-08-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_investigating_officer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='investigating_officer_phone',
            field=models.CharField(max_length=15),
        ),
    ]
