# Generated by Django 5.0.7 on 2024-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_investigating_officer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('family', 'Family'), ('labor', 'Labor'), ('constitutional', 'Constitutional')], max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret')], max_length=255),
        ),
    ]
