# Generated by Django 5.0.7 on 2024-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_case_type_alter_case_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(default='Unknown Court', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='stage_of_case',
            field=models.CharField(choices=[('defence hearing', 'Defence Hearing'), ('withdrawn', 'Withdrawn'), ('hearing', 'Hearing'), ('judgement', 'Judgement'), ('mention', 'Mention'), ('rulling', 'Rulling')], default='mention', max_length=100),
        ),
    ]
