# Generated by Django 5.0.7 on 2024-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_court_name_case_stage_of_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='stage_of_case',
            field=models.CharField(choices=[('defence hearing', 'Defence Hearing'), ('withdrawn', 'Withdrawn'), ('hearing', 'Hearing'), ('judgement', 'Judgement'), ('mention', 'Mention'), ('rulling', 'Rulling')], max_length=100),
        ),
    ]
