# Generated by Django 5.0.7 on 2024-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_case_police_station_case_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_file_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('abduction', 'Abduction'), ('defilement', 'Defilement'), ('neglegence', 'Negligence'), ('legal councelling', 'Legal Councelling'), ('emotional abuse', 'Emotional Abuse'), ('child abuse', 'Child Abuse'), ('physical assault', 'Physical Assault'), ('domestic violence', 'Violence'), ('attempted defilement', 'Attempted Defilement'), ('sodomy', 'Sodomy'), ('rape', 'Rape'), ('juvenile deliquency', 'Juvenile Deliquency'), ('attempted sodomy', 'Attempted Sodomy'), ('attempted rape', 'Attempted Rape'), ('sexual assault', 'Sexual Assault'), ('indicent act', 'Incident Act'), ('sexual harrassment', 'Sexual Harrassment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='stage_of_case',
            field=models.CharField(choices=[('defence hearing', 'Defence Hearing'), ('withdrawn', 'Withdrawn'), ('hearing', 'Hearing'), ('judgement', 'Judgement'), ('mention', 'Mention'), ('rulling', 'Rulling'), ('sentencing_3_years', 'Sentencing for 3 years'), ('jailed_10_years', 'Jailed for 10 years')], max_length=100),
        ),
    ]
