# Generated by Django 5.1.1 on 2024-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_case_county_alter_case_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('mombasa', [('changamwe', 'Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('likoni', 'Likoni'), ('mvita', 'Mvita'), ('nyali', 'Nyali')]), ('kwale', [('matuga', 'Matuga'), ('msambweni', 'Msambweni'), ('kinango', 'Kinango'), ('lunga_lunga', 'Lunga Lunga')]), ('kilifi', [('kilifi_north', 'Kilifi North'), ('kilifi_south', 'Kilifi South'), ('kaloleni', 'Kaloleni'), ('ganze', 'Ganze'), ('malindi', 'Malindi'), ('magarini', 'Magarini'), ('rabai', 'Rabai')]), ('tana_river', [('bura', 'Bura'), ('galole', 'Galole'), ('garsen', 'Garsen')]), ('lamu', [('lamu_east', 'Lamu East'), ('lamu_west', 'Lamu West')]), ('taita_taveta', [('voi', 'Voi'), ('taveta', 'Taveta'), ('mwatate', 'Mwatate'), ('wundanyi', 'Wundanyi')])], max_length=255, null=True),
        ),
    ]
