# Generated by Django 5.1.1 on 2024-10-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_county_alter_case_county_subcounty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='county',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, choices=[('runyu', 'Runyu'), ('miritini', 'Miritini'), ('birikani', 'Birikani'), ('giriamani', 'Giriamani'), ('nairobi area', 'Nairobi Area'), ('centre', 'Centre'), ('mkupe', 'Mkupe'), ('kachimbeni', 'Kachimbani'), ('darajani', 'Darajani'), ('majengo', 'Majengo'), ('kibarani', 'Kibirani'), ('kwashee', 'Kwashee'), ('ganahola', 'Ganahola'), ('aldina', 'Aldina'), ('owino huru', 'Owino Huru'), ('chamunyu jomvu', 'Chamunyu Jomvu'), ('staff', 'Staff'), ('jomvu', 'Jomvu'), ('majengo mapya', 'Majengo Mapya'), ('kwa mwanzia', 'Kwa Mwanzia'), ('kilifi south', 'Kilifi South'), ('likoni', 'Likoni'), ('kisauni', 'Kisauni'), ('nyali', 'Nyali'), ('changamwe', 'Changamwe'), ('kwapunda', 'Kwapunda'), ('bahati', 'Bahati')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
