# Generated by Django 5.1.1 on 2024-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_county_case_county_subcounty_alter_case_sub_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='county',
            field=models.CharField(blank=True, choices=[('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana river', 'Tana River'), ('lamu', 'Lamu'), ('taita-taveta', 'Taita-Taveta')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
