# Generated by Django 5.1.1 on 2024-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_case_county_remove_subcounty_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('changamwe', ' Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('likoni', 'Likoni'), ('mvita', 'Mvita'), ('nyali', 'Nyali'), ('matuga', 'Matuga'), ('msambweni', 'Msambweni'), ('lunga lunga', 'Lunga Lunga'), ('kinango', 'Kinango'), ('kilifi north', 'Kilifi North'), ('kilifi south', 'Kilifi South'), ('malindi', 'Malindi'), ('magarini', 'Magarini'), ('rabai', 'Rabai'), ('kaloleni', 'Kaloleni'), ('ganze', 'Ganze'), ('gazole', 'Galole'), ('bura', 'Bura'), ('garsen', 'Garsen'), ('lamu east', 'Lamu East'), ('lamu west', 'Lamu West'), ('mwatate', 'Mwatate'), ('voi', 'Voi'), ('taveta', 'Taveta'), ('wundanyi', 'Wundanyi')], max_length=255, null=True),
        ),
    ]
