# Generated by Django 5.1.1 on 2024-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_county_alter_case_county_subcounty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='county',
            field=models.CharField(blank=True, choices=[('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana river', 'Tana River'), ('lamu', 'Lamu'), ('taita-taveta', 'Taita-Taveta')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('changamwe', ' Changamwe'), ('jomvu', 'Jomvu'), ('kisauni', 'Kisauni'), ('likoni', 'Likoni'), ('mvita', 'Mvita'), ('nyali', 'Nyali'), ('matuga', 'Matuga'), ('msambweni', 'Msambweni'), ('lunga lunga', 'Lunga Lunga'), ('kinango', 'Kinango'), ('kilifi north', 'Kilifi North'), ('kilifi south', 'Kilifi South'), ('malindi', 'Malindi'), ('magarini', 'Magarini'), ('rabai', 'Rabai'), ('kaloleni', 'Kaloleni'), ('ganze', 'Ganze'), ('gazole', 'Galole'), ('bura', 'Bura'), ('garsen', 'Garsen'), ('lamu east', 'Lamu East'), ('lamu west', 'Lamu West'), ('mwatate', 'Mwatate'), ('voi', 'Voi'), ('taveta', 'Taveta'), ('wundanyi', 'Wundanyi')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
